--
-- Copyright (C) 2008 ASIP Solutions, Inc. All rights reserved. 
-- Generated by ASIP Meister 2.3 on 2016/06/14 17:07:15 
--
-- VHDL Preprocessor version 0.57
-- module     : 32-bit 4-port multiplexor
-- feature    : select one input from n input ports.
-- references : start from scratch
-- author     : Tak. Tokihisa
-- version    : 1.0  : first cut 2002/01/15

-- Functionality : behavior level
--  port
--   data_in  : input data
--   data_out : selected data 
--   sel     : data_out <= data_in0 when sel = "00" else
--            : data_in1 when sel = "01" else
--            : data_in2 when sel = "10" else
--            : data_in3;



library ieee;
  use ieee.std_logic_1164.all;
  use ieee.std_logic_unsigned.all;
  use ieee.std_logic_arith.all;

entity fhm_multiplexor_w32 is
  port (
        data_in0 : in std_logic_vector(31 downto 0);
        data_in1 : in std_logic_vector(31 downto 0);
        data_in2 : in std_logic_vector(31 downto 0);
        data_in3 : in std_logic_vector(31 downto 0);
        sel      : in std_logic_vector(1 downto 0);
        data_out : out std_logic_vector(31 downto 0));
end fhm_multiplexor_w32;

architecture behavior of fhm_multiplexor_w32 is

begin
  process (sel, data_in0, data_in1, data_in2, data_in3)
  begin
	if sel = "00" then
          data_out <= data_in0;
        elsif sel = "01" then
	  data_out <= data_in1;
        elsif sel = "10" then
	  data_out <= data_in2;
        elsif sel = "11" then
	  data_out <= data_in3;
        else
          data_out <= (others => 'X');
        end if;
  end process;  
end behavior;

-----------------------------------------
-- Generated by ASIP Meister ver.2.3.2 --
-----------------------------------------
