--
-- Copyright (C) 2008 ASIP Solutions, Inc. All rights reserved. 
-- Generated by ASIP Meister 2.3 on 2014/09/16 14:10:53 
--

-- Module     : 64-bit Positive Edge Trigger Register
-- Feature    : positive edge trigger
-- References : Started from scratch
-- Author     : Designed by T.Morifuji (c)1997.

-- Version    : 1.0  :

-- Functionality :
--  port
--   clock       : clock port
--   async_reset : asynchronous reset port
--   reset       : synchronous reset port
--   enb         : write enable control
--   data_in     : input data
--   data_out    : output data

-- Comment :

library IEEE;
  use IEEE.std_logic_1164.all;
  use IEEE.std_logic_unsigned.all;

entity fhm_register_w64 is
  port (clock       : in std_logic;
        async_reset : in std_logic;
        reset       : in std_logic;
        enb         : in std_logic;
        data_in     : in std_logic_vector(63 downto 0);
        data_out    : out std_logic_vector(63 downto 0) );
end fhm_register_w64;

architecture logic of fhm_register_w64 is
begin

  process (clock, async_reset)
  begin
    if (async_reset = '1') then
  data_out <=
  	"0000000000000000000000000000000000000000000000000000000000000000";
    elsif (clock'event and clock = '1') then
      if (reset = '1') then
        data_out <= (others => '0');
      elsif (enb = '1') then
        data_out <= data_in;
      end if;
    end if;
  end process;

end logic;


-----------------------------------------
-- Generated by ASIP Meister ver.2.3.2 --
-----------------------------------------
